[package]
name = "oneshot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43", features = [
    "rt-multi-thread",
    "macros",
    "parking_lot",
    "sync",
    "time",
] }
