[package]
name = "spawn_blocking"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = [
    "rt-multi-thread",
    "macros",
    "time",
    "parking_lot",
] }
