[package]
name = "tokio-example"
version = "0.1.0"
edition = "2021"


[dependencies]
# 이유는 모르겠으니 1.43은 오류가 발생한다.
tokio = { version = "~1.42", features = [
    "io-util",
    "macros",
    "net",
    "parking_lot",
    "rt-multi-thread",
] }
